### ISSUE TITLE
MockStatefulServiceReplica.DemoteToActiveSecondaryAsync() fails w/ OperationCanceledException when a stateful service overrides RunAsync(..) w/ proper cancellation token handling

### ISSUE THREAD

**Issue by jonblankenship** [loekd/ServiceFabric.Mocks#103] opened 2020-06-27 02:11 UTC
I have a StatefulService that overrides RunAsync(CancellationToken token) with something like this:

```
protected override async Task RunAsync(CancellationToken cancellationToken)
{
    while (true)
    {
        cancellationToken.ThrowIfCancellationRequested();

        // Do some processing

        await Task.Delay(TimeSpan.FromSeconds(1), cancellationToken);
    }
}
```
Microsoft [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.services.runtime.statefulservicebase.runasync?view=azure-dotnet) states the following:

> If an OperationCanceledException escapes from RunAsync(CancellationToken) and Service Fabric runtime has requested cancellation by signaling cancellationToken passed to RunAsync(CancellationToken), Service Fabric runtime handles this exception and considers it as graceful completion of RunAsync(CancellationToken).

When MockStatefulServiceReplica.DemoteToActiveSecondaryAsync() is called on a replica with a service that overrides RunAsync(..) as shown above, it throws an `OperationCanceledException` with the message `A task was canceled.` and the operation fails.  I think `DemoteToActiveSecondaryAsync()` should handle `OperationCanceledException`s and disregard them.

To reproduce, add the `RunAsync(..)` method above to `StatefulServiceWithReplicaListener` and run test method `TestPromoteActiveSecondaryToPrimaryAsync()` in the test project.

**Comment by loekd** [comment] 2020-07-01 06:30
Hi, thanks for your bug report!
I believe that the unit test `MockStatefulServiceReplicaTests.TestPromoteActiveSecondaryToPrimaryWithRunAsyncOverrideAsync` proves the issue is now resolved. 

Version 4.2.0 should be available soon after posting this.

**Comment by loekd** [comment] 2020-08-17 09:23
closing after no further responses

**Closed by loekd** 2020-08-17 09:23 UTC
Labels: bug
