### ISSUE TITLE
Incorrect implementation of SetAsync in TransactedConcurrentDictionary

### ISSUE THREAD

**Issue by romitsyr** [loekd/ServiceFabric.Mocks#44] opened 2017-12-21 01:39 UTC
Per the documentation of IReliableDictionary
Summary:
Adds a key/value pair to the Reliable Dictionary if the key does not already exist, or updates a key/value pair in the Reliable Dictionary if the key already exists.

However, looks like the mock is implemented to throw if the key does not exist, this deviates from the Service fabric implementation

**Comment by aaronla-ms** [comment] 2018-01-10 19:21
+1, I hit this as well.

**Comment by Marusyk** [comment] 2018-01-11 23:09
https://github.com/Azure/service-fabric-issues#751

**Comment by Marusyk** [comment] 2018-01-11 23:11
Azure/service-fabric-issues#751

**Comment by loekd** [comment] 2018-01-12 07:15
Thanks for reporting this. This issue is fixed in v3.1.4 by @mfmadsen . Please close this issue after confirmation by @romitsyr  and @aaronla-ms .

**Comment by mfmadsen** [comment] 2018-01-12 07:27
I upgraded to the new nuget package version and the issue is fixed in my solution. Hope the fix works for you as well.

**Closed** 2018-01-29 08:07 UTC
