### ISSUE TITLE
Reliable collection is not thread safe, deadlock

### ISSUE THREAD

**Issue by shushengli** [loekd/ServiceFabric.Mocks#70] opened 2018-10-22 23:44 UTC
Hi,
I notice in my test, when multiple threads sets content to the same reliable connect. They deadlock and hang there. It makes multi-thread testing hard.

**Comment by loekd** [comment] 2018-10-24 18:34
Can you please post some code that reproduces the issue?

**Comment by likevi-MSFT** [comment] 2018-10-25 18:41
We've encountered an error where ReliableCollections times out on acquiring a lock.

System.TimeoutException
  HResult=0x80131505
  Message=The operation has timed out.
  Source=ServiceFabric.Mocks
  StackTrace:
   at ServiceFabric.Mocks.ReliableCollections.Lock`1.<Acquire>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceFabric.Mocks.ReliableCollections.LockManager`2.<AcquireLock>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceFabric.Mocks.ReliableCollections.TransactedConcurrentDictionary`2.<AddOrUpdateAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OurCode

**Comment by likevi-MSFT** [comment] 2018-10-25 23:05
We've managed to hit this scenario.
in Lock:AcquireResult()
id: 36
lockMode: Update
result: Denied
_lockOwners.Count = 1
_lockOwners[0] = 35

So it seems there was an attempt to grab the lock before the previous owner (35) released it.

**Comment by likevi-MSFT** [comment] 2018-10-26 00:12
What I see is AcquireResult.Denied in Lock.Acquire() Line 143. The while loop only ran once and the stopwatch shows 34k milliseconds elapsing so the it didn't even get to retry the TryAcquire call.

I've seen instances where TryAcquire is being called before the previous owner calls release and in the case where Acquire has LockMode.Update resulting in TryAcquire returning AcquireResult.Denied as -LockOwners.Count == 1 but does not have the id of the current owner in the TryAcquire.

**Comment by likevi-MSFT** [comment] 2018-10-26 21:07
Did some further debugging and I think I have a better grasp of what might be causing the issue.

Two threads, A and B, are both trying to acquire the same lock.

A enters TryAcquire and gets the lock on _lockOwners.
A returns from TryAcquire. _lockOwners.Count = 1, A is an owner.
B enters TryAcquire and gets the lock on _lockOwners with lockMode Update.
B exits TryAcquire with denied due to lockMode = Update and _lockOwners.Count = 1 and _lockOwners does not contain B.
A enters Release. 
A returns from Release.
B enters Wait and now sets the TokenSource.
B goes into Task.Delay(entire wait duration).
B is expecting it's blocker (A) to call cancel on TokenSource, but the blocker (A) already called Release where it would have called cancel on TokenSource had it been set.
B waits for the entire duration given for the transaction.
B runs out of time to wait and does not retry to acquire the lock.

**Comment by loekd** [comment] 2018-10-27 08:48
@likevi-MSFT, thanks for the investigation and detailed description! Much appreciated.

I've created a unit test in a [branch](https://github.com/loekd/ServiceFabric.Mocks/tree/issue70) which (I believe) reproduces the issue.

**Comment by likevi-MSFT** [comment] 2018-10-27 17:04
Awesome, we'll try to validate the scenario of the unit test. We've been looking into a short term solution using Monitors instead of locking _lockOwners and using CancellationTokenSource as a way to signal waiting threads. It may not be the right thing to do but it has been working for our specific test cases that rely on the MockReliableCollections.

**Comment by loekd** [comment] 2018-10-27 19:12
I've just released version 3.4.0 that has a fix for this lock issue. @shushengli and @likevi-MSFT please let me know if it works, or doesn't work for you.

**Comment by likevi-MSFT** [comment] 2018-10-28 08:29
We will check it out. Thank you for your fast response.

**Comment by likevi-MSFT** [comment] 2018-10-30 00:47
I pulled version 3.4.1 and ran our previously failing test cases a bunch of times and the failure has not reoccurred. 

I'm still interested in learning more about the fix. 

In my investigation I found the issue to be that in the `while` loop of `Acquire` there is nothing preventing another thread from taking action on releasing a lock between the failed `TryAcquire` and `Wait`. My solution to that was to take a lock at the beginning of the `while` loop in `Acquire` and release it at the end of the `while` loop and in `Wait` where the `Task.Delay` occurs (TryAcquire and Wait no longer try to lock before running, they are assumed to only run while the thread already has the lock). This means the other thread cannot release prior to the thread that failed `TryAcquire` from going into `Wait`.

**Comment by loekd** [comment] 2018-10-30 11:14
My solution is to use the intended retry loop to acquire the lock, trying at intervals of 1/10th of the total wait duration. The result is equal to your approach, but doesn't lock as long, allowing other (theoretic) threads (e.g C / D) to enter/exit the monitor while B waits. The downside is a potentially longer wait before the lock is acquired tho (of the duration of the interval at most).

Thanks again for all efforts from your end.

**Comment by likevi-MSFT** [comment] 2018-10-30 22:23
Thank you for the explanation. We've taken the latest version and will be using that now.

**Closed** 2018-11-15 17:58 UTC
